name: Release Announcer
on:
  release:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Release Description
      id: get_release_desc
      run: |
        echo "::set-env name=RELEASE_DESC::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} | jq -r '.body')"

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Новая версия интеграции **Donation Alerts + Streamer.bot**: ${{ github.event.release.tag_name }}

          {{ env.RELEASE_DESC }}

          **Инструкция по настройке**
          {{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}