name: Release Announcer
on:
  release:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Release Description
      id: get_release_desc
      run: echo "::set-output name=desc::$(curl -s <https://api.github.com/repos/$>{{ github.repository }}/releases/${{ github.event.release.id }} | jq '.body')"

    - name: Send Notification to Discord
      uses: appleboy/discord-action@master
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        message: |
        Новая версия интеграции **Donation Alerts + Streamer.bot**: ${{ github.event.release.tag_name }}
        
        ${{ steps.get_release_desc.outputs.desc }}"

        **Инструкция по настройке**
        {{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}